language: r
warnings_are_errors: false
cache: false
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
services:
- xvfb
r:
- release
env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"
  - RGL_USE_NULL=TRUE
  - WARNINGS_ARE_ERRORS=1
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_FORCE_SUGGESTS_=false
  - secure: QZCQBZPErrfUCVisUDV3IyK93fhv06xqKGrJqAWL+KoGEmcc2zrupchGi4q45Vae0A8BCk+hY7OCMOzQzUkxTfTCz4TqyErcQNbnx//7M4UxSWvJJryIvw6Q2R52S2tQOHBlUvbd0BMR4oSx6dfkVPz/YYTUsHZSk77SoO01/uOl203XD6AT4JnFRbCPx6xiWUkAwV9Ik4wNpES4FbvF9/a996omSsGxC+E+YYhQcBmy2/qJdDTB9Lvn1WwrQcHUBf4Fflew5oEeL2bqS5JcIlwzQd7H3aqAoeIk4giQsOPypFPFlyp6MD6hqT1ev5xOc4rgBAJ7yWuaSuFSDJW6Xi2uSE1HnQW3r22/gVYaiTj93Oa2pHPiCVC2BsRJWNbe6w/y5q9j/ZeNMYU7rYxT9eCRI0aLa4KvrBqLaJv1yeI/6Hr1zPp7muKRQ4kzkv0p8fJk9YTsas3NQiHTEHm7Gq2/bvZmhDfCBspp55GQ8fM0rPWZHnC4Z3OT6FoZID+Ha5XZqJfzS/uRgjkqFljwOJW44baNixDarl5A9CCQ2hDEHnzcigWeSVY0Rk0yk7GTlfLrtNvVFDbYv0DdcDMbVRu4jUwviTJryN0u4m8Pu0Ml8I/w7z6zBSzRJbNVcE9VGY4ffkNnR9a0SBHkWLZ6B+ZXho4GdrQhQdv+k0z2m88=
before_install:
- ulimit -n 2048
- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
- export PROJ_DIR=`basename $PWD`
- echo "travis_wait*\.log$" >> .Rbuildignore
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- jags_install || true;
- v8_install || true;
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- export rver=`r_version`; echo $rver ;
- export PACKAGE_NAME=`package_name`
- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
- remove_neuroc_packages
- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
- x=`export_clang_cxx`; eval ${x}
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- clang_cxx
- export cmake_version="3.11"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- export ants_user=neuroconductor
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
  'source', repo = 'http://cran.rstudio.com')" ; fi
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
  ${R_CHECK_ARGS}" ; fi
- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ITKR" ;
  install_missing_remote_deps_all ${ants_user}/ITKR ; gh_binary_install ${ants_user}/ITKR
  ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
  "Installing Missing Deps ANTsRCore" ; install_missing_remote_deps_all ${ants_user}/ANTsRCore;
  gh_binary_install_passive ${ants_user}/ANTsRCore ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
  != "ANTsR" ]]; then echo "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all
  ${ants_user}/ANTsR ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
  ; fi
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- echo $PATH ;
- install_deps_no_suggests
- install_python_requirements ;
- R CMD javareconf ;
- travis_run_cache
script:
- Rscript -e 'install.packages("remotes")'
- Rscript -e 'remotes::install_github("hadley/pkgdown")'
- travis_wait 100 Rscript -e 'pkgdown::build_site()'
after_failure: 
before_deploy: 
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  on:
    branch: master
  github_token: "$GITHUB_TOKEN"
after_deploy: 
