language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: z1iRMPJQXklcphCwAf6TmN/3ko8daqATr+bleiYdCsVpbGI4fa2DDGtzQknJ2BM3rV0XJwKRiFhJ/fGNsnrld7jDdxI3Y14fsy1zTOgWkUlDCS53c60YLCTaMC7+L0Uli1vHPHFnxpgRTp7Gkkiv6xi3dR7PRA/pv2dNO14yUvkuqHszozYJdS8vNDSVKTjz8T0U3w8pwr186/ucn7ALfeZguOEypfBReVMhfu1vN87jVfzcmP9GKpGLr/aQif2PaCs44t/K0NcRe8Yay5l22BGHVgQNZoXkJokMSOu6rz0XyA7OpFfBquSRvZDt9hAe9ooF14xoJ+emOd5nkC5fGyjUSjm2oSyBn52iHIgj5bkGq/2ZbmR0p47E48X7yAgo7nN244yoFZVaMsfYcbMm4s9MO1MDTBSV+c3278+YZzYFEuRID/Qg+CmZri5nmDCZSOJHjDAcMa8Kj31r61NSmxU6y2L8AjAb9esJrwTDwmJeMtLyCaUf8W6PZjQvXlvpYRO0PVP5aVeCf5mHhC7QtH9eTB561RCtDVVEhJh5SbVD3yvHrYOzrvfPvts328cU3LksKk3Asiog4fp7WpdeFq1ruScLpZcJ8OcIneqEep7hbdWJyX+XQZPoQZWzoKFnNiO2ArDOPBR6/7zOhq7tBs+p7CNdzmQo4NNDBu+uDkE=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
