language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: 2NtJffpINIdeKm7+Po5I2J2jq7A+Q0nMWc8pZga65/hy8Jywkz09uJf4skIDvyQHQdvyjSZHs98QkGBcaH3Xp+KGQez5zpJcEge21bjEUNgpONeKJ+9r0sEo+ydU6G8LfUnqJY73CU/pXhOcbooFOT0YdvwYvCyNP9QLAma8X6D6XnIzZLpltgcFK5Mj5E98WOPQLDGTo4meSo+iUeZ4tmrbVwk8vNQhKeGmC17vYvbJyqTXQH7LuvOVIetCC9WSW25EaxYI/vPMNvmoA4lMm8yXpEbcMjb34H8bz43UHk/Hga9t09KMVgYASnyMRm8vm01y7i9K2PMM9szULWCo12qYpxb1zfXikQAlo6rNLCSdp80xSbf4rCpdMU1vzLe/MH1GlES7sziphpUJMQ2CkSE/oMp+1WufcDUqetoB/TRnDBwNLYmDibpJHOAR7kqAufaDxck/LXQ5ym3UxxueOj/28wwKFJzY9YKJZrPCwFQ11V0kkEZf9rq11fAKFLMcH9rrVE08zqiel164cQhbwjgwdarHfadOdXTvN2WpSn4j78P/AmhESmwPXmUn8U1LWR9/ClpR9yGOAHPPJamhOS4et2w7g1hOk2uQTHDUJ+8LAL1Imexa87cup018lqfq1uUiXh+XMIk5o5r9vhp5kAo1aC5OAjVnIXNybTPuNT4=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
