all:
	${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe \
	-e "utils::unzip('camino.zip')";
	rm -rf __MACOSX/;
	cd camino && make clean && make && rm -f Makefile ;	
	${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe copier.R

clean:
	${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe -e "unlink('camino', recursive = TRUE, force = TRUE)"
